// Code auto-generated by cfgeditor.
// DO NOT EDIT!
package sdata

type FunctionF2 struct {
	Score         int32 // 玩家分数
	OpponentScore int32 // 对手分数
	WinDelta      int32 // 获胜分数
	LoseDelta     int32 // 失败分数
}
