// Code auto-generated by cfgeditor.
// DO NOT EDIT!
package sdata

type GlobalOthers struct {
	Key        string          // 配置项
	IntValue   int32           // Int配置值
	FloatValue float32         // Float配置值
	StrValue   string          // Str配置值
	ListValue  []int32         // List配置值
	DictValue  map[int32]int32 // Dict配置值
}
