// Code auto-generated by cfgeditor.
// DO NOT EDIT!
package sdata

type RankForbid struct {
	ForbidID      int32 // 禁入ID
	ForbidTime    int32 // 禁入时长(秒)
	ProbationTime int32 // 敏感期(秒)
	ResetTime     int32 // 重置时间
}
