// Code generated by cfgeditor.
// DO NOT EDIT!
package sdata

type Task struct {
	ID        int32           // 任务ID
	Quest     int32           // 任务内容
	QuestArgs int32           // 任务参数
	Rewards   map[int32]int32 // 任务奖励
}
