// Code auto-generated by cfgeditor.
// DO NOT EDIT!
package sdata

type VersionUpdateAlert struct {
	Channel string // 渠道编号
	Version string // 最新版本号
	Link    string // 跳转链接
	Force   bool   // 是否强制升级
}
